/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InManage;

import InternalPackage.ManagersDB;
import config.Session;
import config.dbconnect;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author mendo
 */
public class AreaForm extends javax.swing.JFrame {

    /**
     * Creates new form AreaForm
     */
    public AreaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        f_status = new javax.swing.JComboBox<>();
        f_cat = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        f_price = new javax.swing.JTextField();
        f_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        canbot = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        f_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose status", "Available", "Unavailable", " ", " " }));
        f_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_statusActionPerformed(evt);
            }
        });
        jPanel4.add(f_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 200, 40));

        f_cat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        f_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Location", "Meals", "Drinks", "Snacks", "Dessert" }));
        f_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_catActionPerformed(evt);
            }
        });
        jPanel4.add(f_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("ADD AREA");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 40));

        f_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_priceActionPerformed(evt);
            }
        });
        jPanel4.add(f_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 200, 40));

        f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameActionPerformed(evt);
            }
        });
        jPanel4.add(f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, 40));

        jLabel3.setText("Area");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel4.setText("Rate");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        canbot.setBackground(new java.awt.Color(173, 216, 230));
        canbot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canbotMouseClicked(evt);
            }
        });
        canbot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("CANCEL");
        canbot.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel4.add(canbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 40));

        edit.setBackground(new java.awt.Color(173, 216, 230));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("EDIT");
        edit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jPanel4.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void f_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_statusActionPerformed

    private void f_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_catActionPerformed

    private void f_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_priceActionPerformed

    private void f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameActionPerformed

    private void canbotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbotMouseClicked
        ManagersDB mdb = new ManagersDB();
        mdb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_canbotMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        dbconnect dbc = new dbconnect();
        boolean isValid = true;
        StringBuilder errorMessages = new StringBuilder();

        // Get input values
        String foodName = f_name.getText().trim();
        String foodPriceText = f_price.getText().trim();
        String foodCategory = f_cat.getSelectedItem().toString().trim();
        String foodStatus = f_status.getSelectedItem().toString().trim();

        // Validate Food Name
        if (foodName.isEmpty()) {
            f_name.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("Food name is required.\n");
            isValid = false;
        } else {
            f_name.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }

        // Validate Food Price
        double foodPrice = 0.0;
        try {
            foodPrice = Double.parseDouble(foodPriceText);
            if (foodPrice < 0) throw new NumberFormatException();
            f_price.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        } catch (NumberFormatException e) {
            f_price.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("Enter a valid positive number for food price.\n");
            isValid = false;
        }

        // Validate Category
        if (f_cat.getSelectedIndex() == 0) {
            f_cat.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("Please select a food category.\n");
            isValid = false;
        } else {
            f_cat.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }

        // Validate Status
        if (f_status.getSelectedIndex() == 0) {
            f_status.setBorder(BorderFactory.createLineBorder(Color.RED));
            errorMessages.append("Please select a food status.\n");
            isValid = false;
        } else {
            f_status.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }

        // Show validation errors if any
        if (!isValid) {
            JOptionPane.showMessageDialog(null, errorMessages.toString(), "Validation Errors", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Insert into database
        try {
            Connection conn = dbc.getConnection();

            String sql = "INSERT INTO area_tbl (a_name, a_rate, a_location, a_status, a_image) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, foodName);
            pst.setDouble(2, foodPrice);
            pst.setString(3, foodCategory);
            pst.setString(4, foodStatus);

            int rows = pst.executeUpdate();

            if (rows > 0) {
                ResultSet keys = pst.getGeneratedKeys();
                int lastId = -1;
                if (keys.next()) {
                    lastId = keys.getInt(1);
                }

                // Log the action
                Session sess = Session.getInstance();
                String userId = sess.getUid();

                if (userId != null && !userId.trim().isEmpty()) {
                    String actions = "Added New Food Item! ID: " + lastId;

                    PreparedStatement logPst = conn.prepareStatement(
                        "INSERT INTO logs (id, actions, date) VALUES (?, ?, ?)"
                    );
                    logPst.setString(1, userId);
                    logPst.setString(2, actions);
                    logPst.setTimestamp(3, Timestamp.valueOf(LocalDateTime.now()));
                    logPst.executeUpdate();
                } else {
                    System.out.println("Warning: Session UID is null or empty. Log not inserted.");
                }

                JOptionPane.showMessageDialog(null, "Food item added successfully!");

                // Clear inputs
                f_name.setText("");
                f_price.setText("");
                f_cat.setSelectedIndex(0);
                f_status.setSelectedIndex(0);

                // Redirect to FoodsDB
                AreasDB fdb = new AreasDB();
                this.dispose();
                fdb.setVisible(true);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canbot;
    private javax.swing.JPanel edit;
    public javax.swing.JComboBox<String> f_cat;
    private javax.swing.JTextField f_name;
    private javax.swing.JTextField f_price;
    public javax.swing.JComboBox<String> f_status;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
