/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InManage;

import config.Session;
import config.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author mendo
 */
public class EditArea extends javax.swing.JFrame {
       int foodId;

    /**
     * Creates new form EditArea
     */
    public EditArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        e_status = new javax.swing.JComboBox<>();
        e_cat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        e_price = new javax.swing.JTextField();
        e_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose status", "Available", "Unavailable", " ", " ", " " }));
        e_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_statusActionPerformed(evt);
            }
        });
        jPanel3.add(e_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 200, 40));

        e_cat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Location", "Ground Floor", "Upper Floor", "Garden Area", "UnderGround" }));
        e_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_catActionPerformed(evt);
            }
        });
        jPanel3.add(e_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("EDIT AREA");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 40));

        e_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_priceActionPerformed(evt);
            }
        });
        jPanel3.add(e_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 200, 40));

        e_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_nameActionPerformed(evt);
            }
        });
        jPanel3.add(e_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, 40));

        jLabel2.setText("Area");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel3.setText("Rate");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(173, 216, 230));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("CANCEL");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 40));

        jPanel4.setBackground(new java.awt.Color(173, 216, 230));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("EDIT");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void e_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_statusActionPerformed

    private void e_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_catActionPerformed

    private void e_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_priceActionPerformed

    private void e_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_nameActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        AreasDB fdb = new AreasDB();
        fdb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
       dbconnect dbc = new dbconnect();
     boolean isValid = true;
     StringBuilder errorMessages = new StringBuilder();

     // Get trimmed input values
     String foodName = e_name.getText().trim();
     String foodPriceText = e_price.getText().trim();
     String foodCategory = e_cat.getSelectedItem().toString().trim();
     String foodStatus = e_status.getSelectedItem().toString().trim();

     // Validate Food Name
     if (foodName.isEmpty()) {
         e_name.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("Food name is required.\n");
         isValid = false;
     } else {
         e_name.setBorder(BorderFactory.createLineBorder(Color.GRAY));
     }

     // Validate Food Price
     double foodPrice = 0.0;
     if (foodPriceText.isEmpty()) {
         e_price.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("Food price is required.\n");
         isValid = false;
     } else {
         try {
             foodPrice = Double.parseDouble(foodPriceText);
             if (foodPrice < 0) {
                 throw new NumberFormatException("Food price cannot be negative.");
             }
             e_price.setBorder(BorderFactory.createLineBorder(Color.GRAY));  // Valid input
         } catch (NumberFormatException e) {
             e_price.setBorder(BorderFactory.createLineBorder(Color.RED));
             errorMessages.append("Enter a valid positive number for food price.\n");
             isValid = false;
         }
     }

     // Validate Category
     if (e_cat.getSelectedIndex() == 0) {
         e_cat.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("Please select a food category.\n");
         isValid = false;
     } else {
         e_cat.setBorder(BorderFactory.createLineBorder(Color.GRAY));
     }

     // Validate Status
     if (e_status.getSelectedIndex() == 0) {
         e_status.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("Please select a food status.\n");
         isValid = false;
     } else {
         e_status.setBorder(BorderFactory.createLineBorder(Color.GRAY));
     }

// Show validation errors
if (!isValid) {
    JOptionPane.showMessageDialog(null, errorMessages.toString(), "Validation Errors", JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    
    Connection conn = dbc.getConnection();
    String sql = "UPDATE area_tbl SET a_name = ?, a_rate = ?, a_location = ?, a_status = ? WHERE a_id = ?";
    PreparedStatement pst = conn.prepareStatement(sql);

  
    pst.setString(1, foodName);           
    pst.setDouble(2, foodPrice);  
    pst.setString(3, foodCategory);
    pst.setString(4, foodStatus);
    pst.setInt(5, foodId); 

    int rows = pst.executeUpdate();
    if (rows > 0) {
        // Log action
        Session sess = Session.getInstance();
        String actions = "Updated Food Item! ID: " + foodId;

        PreparedStatement logPst = conn.prepareStatement("INSERT INTO logs (id, actions, date) VALUES (?, ?, ?)");
        logPst.setString(1, sess.getUid());
        logPst.setString(2, actions);
        logPst.setTimestamp(3, Timestamp.valueOf(LocalDateTime.now()));
        logPst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Food item updated successfully!");

        // Optionally, go back to foods page
        AreasDB fdb = new AreasDB();
        this.dispose();
        fdb.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Update failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> e_cat;
    private javax.swing.JTextField e_name;
    private javax.swing.JTextField e_price;
    public javax.swing.JComboBox<String> e_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
