/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InAdmin;

import InAdmin.*;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;
import config.dbconnect;
import InternalPackage.Dashboard;
import config.Session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class AddUsersForm extends javax.swing.JFrame {

   List<String> existingUsernames = Arrays.asList("cs_user");
   List<String> existingEmails = Arrays.asList("cs_email");
   
    public AddUsersForm() {
    initComponents();
    add_noteadd.setText("Optional");
    add_noteadd.setForeground(new Color(153, 153, 153));
    }
    

    
    Color hover = new Color(153,153,153);  
    Color defbutton = new Color(102,102,102);  
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void resetButtonColor(JButton button){
        button.setBackground(defbutton);
    }
    Color lightGray = new Color(211, 211, 211);
    Color lightBlue = new Color(173, 216, 230);
    Color charcoal = new Color(28, 28, 28);
    Color teal = new Color(0, 128, 128);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        cancelregformButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        add_uname = new javax.swing.JTextField();
        add_fname = new javax.swing.JTextField();
        add_email = new javax.swing.JTextField();
        add_contact = new javax.swing.JTextField();
        add_address = new javax.swing.JTextField();
        add_noteadd = new javax.swing.JTextField();
        add_lname = new javax.swing.JTextField();
        add_conpass = new javax.swing.JPasswordField();
        add_pass = new javax.swing.JPasswordField();
        add_type = new javax.swing.JComboBox<>();
        cancel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        signup = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Last Name*");

        cancelregformButton.setBackground(new java.awt.Color(102, 102, 102));
        cancelregformButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelregformButton.setText("Cancel");
        cancelregformButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelregformButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelregformButtonMouseExited(evt);
            }
        });
        cancelregformButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelregformButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Confirm Password*");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Username*");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Contact Number*");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Email Address*");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Password*");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Note Address*");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Address*");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Last Name*");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Type*");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("First Name*");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        jPanel2.add(add_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 180, 30));

        add_fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                add_fnameFocusLost(evt);
            }
        });
        jPanel2.add(add_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, 30));
        jPanel2.add(add_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, 30));
        jPanel2.add(add_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, 30));
        jPanel2.add(add_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 180, 30));
        jPanel2.add(add_noteadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 180, 30));

        add_lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                add_lnameFocusLost(evt);
            }
        });
        jPanel2.add(add_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, 30));

        add_conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_conpassActionPerformed(evt);
            }
        });
        jPanel2.add(add_conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 180, 30));
        jPanel2.add(add_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 180, 30));

        add_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Manager", "Customer", " " }));
        jPanel2.add(add_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 180, 30));

        cancel.setBackground(new java.awt.Color(173, 216, 230));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Cancel");
        cancel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 7, -1, -1));

        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 100, 30));

        signup.setBackground(new java.awt.Color(173, 216, 230));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMouseExited(evt);
            }
        });
        signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Sign Up");
        signup.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 7, -1, -1));

        jPanel2.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("CREATE NEW USERS FORM");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 40));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 10, 10));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 10, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelregformButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelregformButtonMouseEntered
        cancelregformButton.setBackground(hover);
    }//GEN-LAST:event_cancelregformButtonMouseEntered

    private void cancelregformButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelregformButtonMouseExited
        cancelregformButton.setBackground(defbutton);
    }//GEN-LAST:event_cancelregformButtonMouseExited

    private void cancelregformButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelregformButtonActionPerformed

        Dashboard db = new Dashboard();
        this.dispose();
        db.setVisible(true);

    }//GEN-LAST:event_cancelregformButtonActionPerformed

    private void add_fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add_fnameFocusLost

    }//GEN-LAST:event_add_fnameFocusLost

    private void add_lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_add_lnameFocusLost

    }//GEN-LAST:event_add_lnameFocusLost

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        Dashboard db = new Dashboard();
        this.dispose();
        db.setVisible(true);

    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setBackground(lightGray);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setBackground(lightBlue);
    }//GEN-LAST:event_cancelMouseExited

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
       dbconnect dbc = new dbconnect();
        boolean isValid = true;
        StringBuilder errorMessages = new StringBuilder();

    // Get trimmed input values
    String fname = add_fname.getText().trim();
    String lname = add_lname.getText().trim();
    String email = add_email.getText().trim();
    String contact = add_contact.getText().trim();
    String username = add_uname.getText().trim();
    String password = new String(add_pass.getPassword());
    String confirmPassword = new String(add_conpass.getPassword());
    String address = add_address.getText().trim();
    String noteAddress = add_noteadd.getText().trim();
    String accountType = add_type.getSelectedItem().toString();

    // Validate First Name
    if (fname.isEmpty()) {
        add_fname.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("First name is required.\n");
        isValid = false;
    } else {
        add_fname.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Last Name
    if (lname.isEmpty()) {
        add_lname.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Last name is required.\n");
        isValid = false;
    } else {
        add_lname.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Email
    if (email.isEmpty()) {
        add_email.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Email is required.\n");
        isValid = false;
    } else if (!email.matches("^[\\w._%+-]+@[\\w.-]+\\.[a-zA-Z]{2,6}$")) {
        add_email.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Invalid email format.\n");
        isValid = false;
    } else {
        add_email.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Account Type
    if (add_type.getSelectedIndex() == 0) {
        add_type.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Please select an account type.\n");
        isValid = false;
    } else {
        add_type.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Contact Number
    if (!contact.matches("\\d{11}")) {
        add_contact.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Contact number must be 11 digits.\n");
        isValid = false;
    } else {
        add_contact.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Username
    if (username.isEmpty()) {
        add_uname.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Username is required.\n");
        isValid = false;
    } else {
        add_uname.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Password
    if (password.length() < 8) {
        add_pass.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Password must be at least 8 characters.\n");
        isValid = false;
    } else {
        add_pass.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Confirm Password
    if (!password.equals(confirmPassword)) {
        add_conpass.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Passwords do not match.\n");
        isValid = false;
    } else {
        add_conpass.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    // Validate Address
    if (address.isEmpty()) {
        add_address.setBorder(BorderFactory.createLineBorder(Color.RED));
        errorMessages.append("Address is required.\n");
        isValid = false;
    } else {
        add_address.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }   

    // Show errors if any
    if (!isValid) {
        JOptionPane.showMessageDialog(null, errorMessages.toString(), "Validation Errors", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Insert into database
    try {
        Connection conn = dbc.getConnection();

        // Path to default profile picture
        String profilePicture = "pfpimage/default.jpg";  // use relative path inside the "profile_picture" folder

        String sql = "INSERT INTO customer (cs_fname, cs_lname, cs_email, cs_contact, cs_user, cs_pass, cs_address, cs_type, cs_status, profile_picture) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement pst = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        pst.setString(1, fname);
        pst.setString(2, lname);
        pst.setString(3, email);
        pst.setString(4, contact);
        pst.setString(5, username);
        pst.setString(6, password);  // Consider hashing passwords in real applications
        pst.setString(7, address);
        pst.setString(8, accountType);
        pst.setString(9, "Pending");
        pst.setString(10, profilePicture);  // Use the default image path

        int rows = pst.executeUpdate();
        if (rows > 0) {
            ResultSet keys = pst.getGeneratedKeys();
            int lastId = -1;
            if (keys.next()) {
                lastId = keys.getInt(1);
            }

            // Log action
            Session sess = Session.getInstance();
            String logMsg = "Created New User Account! ID: " + lastId;

            PreparedStatement logPst = conn.prepareStatement("INSERT INTO logs (id, actions, date) VALUES (?, ?, ?)");
            logPst.setString(1, sess.getUid());
            logPst.setString(2, logMsg);
            logPst.setTimestamp(3, Timestamp.valueOf(LocalDateTime.now()));
            logPst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Registration successful!");

            // Go to dashboard
            Dashboard db = new Dashboard();
            this.dispose();
            db.setVisible(true);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_signupMouseClicked

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
        signup.setBackground(lightGray);
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseExited
        signup.setBackground(lightBlue);
    }//GEN-LAST:event_signupMouseExited

    private void add_conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_conpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_address;
    private javax.swing.JPasswordField add_conpass;
    private javax.swing.JTextField add_contact;
    private javax.swing.JTextField add_email;
    private javax.swing.JTextField add_fname;
    private javax.swing.JTextField add_lname;
    private javax.swing.JTextField add_noteadd;
    private javax.swing.JPasswordField add_pass;
    private javax.swing.JComboBox<String> add_type;
    private javax.swing.JTextField add_uname;
    private javax.swing.JPanel cancel;
    private javax.swing.JButton cancelregformButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel signup;
    // End of variables declaration//GEN-END:variables
}
