/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InAdmin;

import InAdmin.*;
import InternalPackage.Dashboard;
import config.Session;
import config.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author SCC-COLLEGE
 */
public class EditUsers extends javax.swing.JFrame {

    /**
     * Creates new form EditUsers
     */
     List<String> existingEmails = Arrays.asList("cs_email");
    public EditUsers() {
        initComponents();
    }
    Color hover = new Color(153,153,153);  
    Color defbutton = new Color(102,102,102);  
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void resetButtonColor(JButton button){
        button.setBackground(defbutton);
    }
    Color lightGray = new Color(211, 211, 211);
    Color lightBlue = new Color(173, 216, 230);
    Color charcoal = new Color(28, 28, 28);
    Color teal = new Color(0, 128, 128);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        add_contact = new javax.swing.JTextField();
        add_fname = new javax.swing.JTextField();
        add_email = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logintext = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(add_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 160, 30));
        jPanel2.add(add_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 160, 30));
        jPanel2.add(add_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 160, 30));
        jPanel2.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 160, 30));

        jLabel2.setText("First Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel3.setText("Status");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel4.setText("Email Address");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel5.setText("Contact Number");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        update.setBackground(new java.awt.Color(173, 216, 230));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Update");
        update.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconss/logout (2).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        logintext.setBackground(new java.awt.Color(173, 216, 230));
        logintext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logintext.setForeground(new java.awt.Color(153, 153, 153));
        logintext.setText("EDIT INFORMATION");
        jPanel2.add(logintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 540, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         Dashboard db = new Dashboard();
        this.dispose();
        db.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        dbconnect dbc = new dbconnect();
        boolean isValid = true;

     String emails = add_email.getText().trim();
     StringBuilder errorMessages = new StringBuilder();

     // First Name Validation
     if (add_fname.getText().isEmpty()) {
         add_fname.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("First name is required.\n");
         isValid = false;
     } else {
         add_fname.setBorder(BorderFactory.createLineBorder(Color.GRAY));
     }

     // Email Validation
     if (add_email.getText().isEmpty()) {
         add_email.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("Email is required.\n");
         isValid = false;
     } else {
         add_email.setBorder(BorderFactory.createLineBorder(Color.GRAY));
     }

     // Check if Email already exists in the list
     if (existingEmails.contains(add_email.getText())) {
         add_email.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("Email is already registered.\n");
         isValid = false;
     }

     // Email Format Validation
     if (!add_email.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$")) {
         add_email.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("Email must be in the format 'username@domain.com'.\n");
         isValid = false;
     } else {
         add_email.setBorder(BorderFactory.createLineBorder(Color.GRAY));
     }

     // Contact Number Validation
     if (add_contact.getText().isEmpty()) {
         add_contact.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("Contact number is required.\n");
         isValid = false;
     } else {
         add_contact.setBorder(BorderFactory.createLineBorder(Color.GRAY));
     }

     String contactNumber = add_contact.getText().trim();
     if (!contactNumber.matches("\\d{11}")) {
         add_contact.setBorder(BorderFactory.createLineBorder(Color.RED));
         errorMessages.append("Contact number must contain exactly 11 digits.\n");
         isValid = false;
     } else {
         add_contact.setBorder(BorderFactory.createLineBorder(Color.GRAY));
     }


     if (!isValid) {
         JOptionPane.showMessageDialog(null, errorMessages.toString(), "Error", JOptionPane.ERROR_MESSAGE);
     } else {

         String userStatus = status.getText().trim(); 

         JOptionPane.showMessageDialog(null, "Update Completed", "Success", JOptionPane.INFORMATION_MESSAGE);

         // ✅ Correct SQL statement
         if (dbc.insertData("UPDATE customer SET cs_fname = '" + add_fname.getText() + "', "
                 + "cs_email = '" + add_email.getText() + "', "
                 + "cs_contact = '" + add_contact.getText() + "', "
                 + "cs_status = '" + userStatus + "' "
                 + "WHERE cs_email = '" + add_email.getText() + "'") == 1) {

             String actions = "Updated account Information!";
             try (Connection conn = dbc.getConnection();
                  PreparedStatement logStmt = conn.prepareStatement(
                          "INSERT INTO logs (id, actions, date) VALUES (?, ?, ?)")) {

                 Session sess = Session.getInstance();
                 logStmt.setString(1, sess.getUid());
                 logStmt.setString(2, actions);
                 logStmt.setTimestamp(3, Timestamp.valueOf(LocalDateTime.now()));
                 logStmt.executeUpdate();

             } catch (SQLException logEx) {
                 System.out.println("Log Insertion Error: " + logEx.getMessage());
             }

             Dashboard db = new Dashboard();
             this.dispose();
             db.setVisible(true);

         } else {
             JOptionPane.showMessageDialog(null, "Database update failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
         }
     }

     
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(lightGray);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(lightBlue);
    }//GEN-LAST:event_updateMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_contact;
    private javax.swing.JTextField add_email;
    private javax.swing.JTextField add_fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logintext;
    private javax.swing.JTextField status;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
